version: "3"

services:

  db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    restart: always
    environment:
     MYSQL_DATABASE: accountdb
     MYSQL_USER: root
     MYSQL_ROOT_PASSWORD: root